### ISSUE TITLE
Test tier is hanging

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#1426]
Choose TCGA-KIRC
Choose Computed Tomography
Click Collection Cart button -> yellow
expand cases
Remove Computed Tomography
Click Collection Cart button

```
jquery-3.7.1.min.js:2 jQuery.Deferred exception: row is not defined ReferenceError: row is not defined
    at HTMLTableRowElement.<anonymous> (https://storage.googleapis.com/idc-test-web-static-files/static/js/tables.js:1979:21)
    at Function.each (https://storage.googleapis.com/idc-test-web-static-files/static/js/libs/jquery-3.7.1.min.js:2:3129)
    at ce.fn.init.each (https://storage.googleapis.com/idc-test-web-static-files/static/js/libs/jquery-3.7.1.min.js:2:1594)
    at window.updateTableCounts (https://storage.googleapis.com/idc-test-web-static-files/static/js/tables.js:1957:41)
    at updateTableCountsAndGlobalCartCounts (https://storage.googleapis.com/idc-test-web-static-files/static/js/cartutils.js:260:16)
    at https://storage.googleapis.com/idc-test-web-static-files/static/js/cartutils.js:351:17
    at e (https://storage.googleapis.com/idc-test-web-static-files/static/js/libs/jquery-3.7.1.min.js:2:27028)
    at t (https://storage.googleapis.com/idc-test-web-static-files/static/js/libs/jquery-3.7.1.min.js:2:27330) undefined
```

**Comment by fedorov** [comment]
Revisit after test tier is ready for testing. It is not right now.

**Comment by s-paquette** [comment]
This has been addressed via numerous restructures of the code.
