### ISSUE TITLE
Unable to create a cohort with all collections present 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#628]
The selection of all collections then trying to save a cohort will cause the red notification error to appear stating, "Failed to save cohort!"

Video of test run is displayed below,

https://user-images.githubusercontent.com/16824894/118569491-0a1af800-b748-11eb-83ec-0d98c0479ed3.mov

**Comment by G-White-ISB** [comment]
I've traced this to the limit in the MySQL column 'value' in the table cohorts_filter:
Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/cohorts/utils.py", line 186, in _save_cohort
    Filter.objects.bulk_create(filter_set)
  File "/home/vagrant/www/lib/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/www/lib/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/home/vagrant/www/lib/django/db/models/query.py", line 1211, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/vagrant/www/lib/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/www/lib/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/vagrant/www/lib/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'value' at row 2")

**Comment by s-paquette** [comment]
So this is what I was saying on Tuesday--we need to decide if we want to have a limit on allowed size of a list of cohort filter values, or not. If we want to have a limit, you'd need to enforce that on the front end. It can be a per-attribute level, so having one attribute with a lot of values won't impose a limit on the rest.

The alternative is I raise the cap, or, convert the field to text (which has a large limit on the order of megabytes, as I recall). 

@fedorov @wlongabaugh thoughts?

**Comment by G-White-ISB** [comment]
In my opinion for both user experience and ease of front end development it would be better to increase the size of this column or convert it to text.

**Comment by fedorov** [comment]
Is this related to #622?

**Comment by s-paquette** [comment]
@fedorov  Yes--the same ticket keeps being re-entered. It'd be best if we could consolidate this into a single ticket.

**Comment by G-White-ISB** [comment]
They are related but are distinct. #622 is for an error in  applying a large filter. This had to do with calling the server through GET instead of POST. This occurs prior to trying to save a cohort. I have a fix for this. THIS ticket is for saving a cohort with a longish list of attribute values after filtering is applied.

**Comment by s-paquette** [comment]
Okay, for that purpose we can keep them separate, in terms of back-end vs. front end.

**Comment by madelyngreyes** [comment]
![Screen Shot 2021-06-07 at 8 31 12 AM](https://user-images.githubusercontent.com/16824894/121017122-e9542a00-c76a-11eb-853b-d4847e842625.png)

Cohort with all collections selected created above.
